# See https://docs.docker.com/compose/compose-file/compose-versioning/ for version
version: "3.8"
services:

    db:
        image: mysql
        container_name: db_docker_atlas
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_atlas
        restart: always
        depends_on:
            - db
        ports:
            - 8082:80
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 300M
        networks:
            - dev

    www:
        build: php
        container_name: www_docker_atlas
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ../:/var/www
        restart: always
        networks:
            - dev


    maildev:
        image: maildev/maildev
        container_name: maildev_docker_atlas
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        restart: always
        networks:
            - dev


networks:
    dev:

volumes:
    db-data:
